version: '3'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: qwerty12!
      POSTGRES_DB: user_testing_application
    ports:
      - "5432:5432"
